id = "ezio"
name = "Ezio"
version = "0.0.1"
schema_version = 1
authors = ["Derek Santolo github.com/dsantolo"]
description = "The Ezio theme for Zed."
repository = "https://github.com/dsantolo/ezio-zed"
